AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: search codepipeline
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./LambdaCode
      Description: 'Lambda function for search'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::574875490087:role/service-role/AWSCodePipelineServiceRole-us-east-1-smart-photo-frontend'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1