AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: search codepipeline
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lambda_function
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: 'Lambda function for search'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::574875490087:role/service-role/search-role-m44arr9o'
      Events:
        toS3:
          Type: Api
          Properties:
            Path: /{bucket}
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
      Policies:
        - AWSLambdaExecute
        - CloudWatchLogsFullAccess
        - AmazonRekognitionFullAccess
        - AmazonLexFullAccess
        - AmazonS3FullAccess
        - AmazonOpenSearchServiceFullAccess
        - AmazonAPIGatewayAdministrator
  LF2:
    Type: 'AWS::Serverless::Function'
    Properties:
    Runtime: python3.9
    CodeUri: .
    Handler: put.lambda_handler
    FunctionName: put
    Role: 'arn:aws:iam::574875490087:role/service-role/index-photos-role-0xtl6p49'
    Environment:
      Variables:
        REGIOM: us-east-1
    Events:
        photosbucket112:
          Type: S3
          Properties:
            Method: put
    Environment:
      Variables:
        REGION: us-east-1
     Policies:
      - AWSLambdaExecute
      - CloudWatchLogsFullAccess
      - AmazonRekognitionFullAccess
      - AmazonLexFullAccess
      - AmazonS3FullAccess
      - AmazonOpenSearchServiceFullAccess
      - AmazonAPIGatewayAdministrator